name: kidsapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^1.1.2
  font_awesome_flutter: ^9.0.0
  page_transition: ^1.1.7+6
  material_dialogs: ^1.0.0
  http: ^0.12.2
  provider: ^4.3.3
  dio: ^3.0.10
  page_indicator: ^0.3.0
  permission_handler: ^6.1.1
  flutter_staggered_grid_view: ^0.3.4
  shared_preferences: ^2.0.5
  email_validator: ^2.0.1
  geolocator: ^7.0.1
  location_permissions: ^3.0.0+1
  geocoder: ^0.2.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Group400.png
    - assets/images/Group 39.png
    - assets/images/Group 72.png
    - assets/images/Rectangle129.jpg
    - assets/images/dua-hands.png
    - assets/images/ramdan.png
    - assets/images/salah.png
    - assets/images/weather.png
    - assets/images/quran.png
    - assets/images/duaa.png
    - assets/images/moshaf.png
    - assets/images/bal.png
    - assets/images/ab.png
    - assets/images/Group 77.png
    - assets/images/Mask Group 1.png
    - assets/images/Group 2386.png
    - assets/images/Mask Group 3.png
    - assets/images/Group 2332.png
    - assets/images/Group 2333.png
    - assets/images/Group 705.png
    - assets/images/Group 709.png
    -  assets/images/Group 804.png
    -  assets/images/Group 808.png
    -  assets/images/Group 813.png
    -  assets/images/Group 815.png
    -  assets/images/Group 795.png
    -  assets/images/Group 2318.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
